# Generated by Django 3.2.5 on 2021-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='make a blog!!SS', max_length=255),
        ),
    ]
