# Generated by Django 3.2.5 on 2021-08-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmblog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click above link to read blog post !!', max_length=252),
        ),
    ]
