# Generated by Django 3.2.5 on 2021-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmblog', '0010_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=252),
        ),
    ]
